### ISSUE TITLE
Incompatible with recent Jupyter book

### ISSUE THREAD

**Issue by daikitag** [tskit-dev/tskit-book-theme#7]
I'm now trying to use `tskit-book-theme`, but it uses `pydata-sphinx-theme` version 0.8, which is compatible with the recent `sphinx-book-theme` version 1x. Thus, it seems that I can only use `jupyter-book` version 0.13, and not version >=0.14. I understand that it might take some time, but would it be possible for you to upgrade `tskit-book-theme`, such that it can be used with the latest `pydata-sphinx-theme`? Thank you for your consideration.

**Comment by benjeffery** [comment]
That's what #6 is - but I didn't make that very clear!

**Comment by daikitag** [comment]
Thanks! Then I'll close this issue now.
